{
  "build": {
    "command": "npm run build",
    "publish": "build/client",
    "environment": {
      "NODE_VERSION": "20"
    }
  },
  "redirects": [
    {
      "from": "/*",
      "to": "/index.html",
      "status": 200
    }
  ]
}
